services:
  mongo:
    image: mongo:latest
    container_name: mongo-car-api
    restart: always
    ports:
      - "27017:27017"  # Map external 27018 to internal 27017
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: car-api
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"  # Use service name inside Docker
    ports:
      - "8080:8080"

volumes:
  mongo-data:
