version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-car-api
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Use named volume

  app:
    build: .
    container_name: car-api
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    ports:
      - "8080:8080"

# âœ… Define the volume here
volumes:
  mongo-data:
